**pandas - DataFrame objects**

* A DataFrame object represents a spreadsheet, with cell values, column names and row index labels. 
* You can define expressions to compute columns based on other columns, create pivot-tables, group rows, draw graphs, etc. 
* You can see `DataFrame`s as dictionaries of `Series`.

# Setup

Use the `setup.ipnb` notebook to import `pandas` and `numpy`. Furthermore, use the same `setup.ipynb` notebook to set the path variables, such as `DATA_PATH` and `RESULTS_PATH`.

In [1]:
%run setup.ipynb

## Creating a `DataFrame`
You can create a DataFrame by passing a dictionary of `Series` objects:

In [2]:
people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "yue", "ditsuhi"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["alice", "yue", "ditsuhi"], name="year"),
    "children": pd.Series([0, 3], index=["yue", "ditsuhi"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "yue"]),
}
people = pd.DataFrame(people_dict)
people

weight  birthyear  children    hobby
alice        68       1984       NaN   Biking
ditsuhi     112       1992       3.0      NaN
yue          83       1985       0.0  Dancing

A few things to note:
* the `Series` were automatically aligned based on their index,
* missing values are represented as `NaN`,
* `Series` names are ignored (the name `"year"` was dropped),
* `DataFrame`s are displayed nicely in Jupyter notebooks.

You can access columns pretty much as you would expect. They are returned as `Series` objects:

In [3]:
people["birthyear"]

alice      1984
ditsuhi    1992
yue        1985
Name: birthyear, dtype: int64

You can also get multiple columns at once:

In [4]:
people[["birthyear", "hobby"]]

birthyear    hobby
alice         1984   Biking
ditsuhi       1992      NaN
yue           1985  Dancing

If you pass a list of columns and/or index row labels to the `DataFrame` constructor, it will guarantee that these columns and/or rows will exist, in that order, and no other column/row will exist. For example:

In [5]:
d2 = pd.DataFrame(
        people_dict,
        columns=["birthyear", "weight", "height"],
        index=["alice", "yue", "eli"]
     )
d2

birthyear  weight height
alice     1984.0    68.0    NaN
yue       1985.0    83.0    NaN
eli          NaN     NaN    NaN

Another convenient way to create a `DataFrame` is to pass all the values to the constructor as an `ndarray`, or a list of lists, and specify the column names and row index labels separately:

In [6]:
values = [
            [1985, np.nan, "Biking",   68],
            [1984, 3,      "Dancing",  83],
            [1992, 0,      np.nan,    112]
         ]
d3 = pd.DataFrame(
        values,
        columns=["birthyear", "children", "hobby", "weight"],
        index=["alice", "yue", "ditsuhi"]
     )
d3

birthyear  children    hobby  weight
alice         1985       NaN   Biking      68
yue           1984       3.0  Dancing      83
ditsuhi       1992       0.0      NaN     112

To specify missing values, you can either use `np.nan` or NumPy's masked arrays:

In [7]:
masked_array = np.ma.asarray(values, dtype=object)
masked_array[(0, 2), (1, 2)] = np.ma.masked
d3 = pd.DataFrame(
        masked_array,
        columns=["birthyear", "children", "hobby", "weight"],
        index=["alice", "yue", "ditsuhi"]
     )
d3

birthyear children    hobby weight
alice        1985      NaN   Biking     68
yue          1984        3  Dancing     83
ditsuhi      1992        0      NaN    112

Instead of an `ndarray`, you can also pass a `DataFrame` object:

In [8]:
d4 = pd.DataFrame(
         d3,
         columns=["hobby", "children"],
         index=["alice", "yue",]
     )
d4

hobby children
alice   Biking      NaN
yue    Dancing        3

It is also possible to create a `DataFrame` with a dictionary (or list) of dictionaries (or list):

In [9]:
people = pd.DataFrame({
    "birthyear": {"alice":1985, "yue": 1984, "ditsuhi": 1992},
    "hobby": {"alice":"Biking", "yue": "Dancing"},
    "weight": {"alice":68, "yue": 83, "ditsuhi": 112},
    "children": {"yue": 3, "ditsuhi": 0}
})
people

birthyear    hobby  weight  children
alice         1985   Biking      68       NaN
yue           1984  Dancing      83       3.0
ditsuhi       1992      NaN     112       0.0

## Multi-indexing
If all columns are tuples of the same size, then they are understood as a multi-index. The same goes for row index labels. For example:

In [10]:
d5 = pd.DataFrame(
  {
    ("public", "birthyear"):
        {("Paris","alice"):1985, ("Paris","yue"): 1984, ("London","ditsuhi"): 1992},
    ("public", "hobby"):
        {("Paris","alice"):"Biking", ("Paris","yue"): "Dancing"},
    ("private", "weight"):
        {("Paris","alice"):68, ("Paris","yue"): 83, ("London","ditsuhi"): 112},
    ("private", "children"):
        {("Paris", "alice"):np.nan, ("Paris","yue"): 3, ("London","ditsuhi"): 0}
  }
)
d5

public          private         
               birthyear    hobby  weight children
Paris  alice        1985   Biking      68      NaN
       yue          1984  Dancing      83      3.0
London ditsuhi      1992      NaN     112      0.0

You can now get a `DataFrame` containing all the `"public"` columns very simply:

In [11]:
d5["public"]

birthyear    hobby
Paris  alice         1985   Biking
       yue           1984  Dancing
London ditsuhi       1992      NaN

In [12]:
d5["public", "hobby"]  # Same result as d5["public"]["hobby"]

Paris   alice       Biking
        yue        Dancing
London  ditsuhi        NaN
Name: (public, hobby), dtype: object

## Dropping a level
Let's look at `d5` again:

In [13]:
d5

public          private         
               birthyear    hobby  weight children
Paris  alice        1985   Biking      68      NaN
       yue          1984  Dancing      83      3.0
London ditsuhi      1992      NaN     112      0.0

There are two levels of columns, and two levels of indices. We can drop a column level by calling `droplevel()` (the same goes for indices):

In [14]:
d5.columns = d5.columns.droplevel(level = 0)
d5

birthyear    hobby  weight  children
Paris  alice         1985   Biking      68       NaN
       yue           1984  Dancing      83       3.0
London ditsuhi       1992      NaN     112       0.0

## Transposing
You can swap columns and indices using the `T` attribute:

In [15]:
d6 = d5.T
d6

Paris           London
            alice      yue ditsuhi
birthyear    1985     1984    1992
hobby      Biking  Dancing     NaN
weight         68       83     112
children      NaN      3.0     0.0

## Stacking and unstacking levels
Calling the `stack()` method will push the lowest column level after the lowest index:

In [16]:
d7 = d6.stack()
d7

London    Paris
birthyear alice      NaN     1985
          ditsuhi   1992      NaN
          yue        NaN     1984
hobby     alice      NaN   Biking
          yue        NaN  Dancing
weight    alice      NaN       68
          ditsuhi    112      NaN
          yue        NaN       83
children  ditsuhi    0.0      NaN
          yue        NaN      3.0

Note that many `NaN` values appeared. This makes sense because many new combinations did not exist before (eg. there was no `bob` in `London`).

Calling `unstack()` will do the reverse, once again creating many `NaN` values.

In [17]:
d8 = d7.unstack()
d8

London                Paris                 
           alice ditsuhi  yue   alice ditsuhi      yue
birthyear    NaN    1992  NaN    1985     NaN     1984
children     NaN     0.0  NaN     NaN     NaN      3.0
hobby        NaN     NaN  NaN  Biking     NaN  Dancing
weight       NaN     112  NaN      68     NaN       83

If we call `unstack` again, we end up with a `Series` object:

In [18]:
d9 = d8.unstack()
d9

London  alice    birthyear        NaN
                 children         NaN
                 hobby            NaN
                 weight           NaN
        ditsuhi  birthyear       1992
                 children         0.0
                 hobby            NaN
                 weight           112
        yue      birthyear        NaN
                 children         NaN
                 hobby            NaN
                 weight           NaN
Paris   alice    birthyear       1985
                 children         NaN
                 hobby         Biking
                 weight            68
        ditsuhi  birthyear        NaN
                 children         NaN
                 hobby            NaN
                 weight           NaN
        yue      birthyear       1984
                 children         3.0
                 hobby        Dancing
                 weight            83
dtype: object

The `stack()` and `unstack()` methods let you select the `level` to stack/unstack. You can even `stack/unstack` multiple levels at once:

In [19]:
d10 = d9.unstack(level = (0,1))
d10

London                Paris                 
           alice ditsuhi  yue   alice ditsuhi      yue
birthyear    NaN    1992  NaN    1985     NaN     1984
children     NaN     0.0  NaN     NaN     NaN      3.0
hobby        NaN     NaN  NaN  Biking     NaN  Dancing
weight       NaN     112  NaN      68     NaN       83

## Most methods return modified copies
As you may have noticed, the `stack()` and `unstack()` methods do not modify the object they apply to. Instead, they work on a copy and return that copy. This is true of most methods in pandas.

## Accessing rows
Let's go back to the `people` `DataFrame`:

In [20]:
people

birthyear    hobby  weight  children
alice         1985   Biking      68       NaN
yue           1984  Dancing      83       3.0
ditsuhi       1992      NaN     112       0.0

The `loc` attribute lets you access rows instead of columns. The result is a `Series` object in which the `DataFrame`'s column names are mapped to row index labels:

In [21]:
people.loc["yue"]

birthyear       1984
hobby        Dancing
weight            83
children         3.0
Name: yue, dtype: object

You can also access rows by integer location using the `iloc` attribute:

In [22]:
people.iloc[2]

birthyear    1992
hobby         NaN
weight        112
children      0.0
Name: ditsuhi, dtype: object

You can also get a slice of rows, and this returns a `DataFrame` object:

In [23]:
people.iloc[1:3]

birthyear    hobby  weight  children
yue           1984  Dancing      83       3.0
ditsuhi       1992      NaN     112       0.0

Finally, you can pass a `boolean array` to get the matching rows:

In [24]:
people[np.array([True, False, True])]

birthyear   hobby  weight  children
alice         1985  Biking      68       NaN
ditsuhi       1992     NaN     112       0.0

This is most useful when combined with `boolean` expressions:

In [25]:
people[people["birthyear"] < 1990]

birthyear    hobby  weight  children
alice       1985   Biking      68       NaN
yue         1984  Dancing      83       3.0

## Adding and removing columns
You can generally treat `DataFrame` objects like dictionaries of `Series`, so the following work fine:

In [26]:
people

birthyear    hobby  weight  children
alice         1985   Biking      68       NaN
yue           1984  Dancing      83       3.0
ditsuhi       1992      NaN     112       0.0

In [27]:
people["age"] = 2018 - people["birthyear"]  # adds a new column "age"
people["over 30"] = people["age"] > 30      # adds another column "over 30"
birthyears = people.pop("birthyear")
del people["children"]

people

hobby  weight  age  over 30
alice     Biking      68   33     True
yue      Dancing      83   34     True
ditsuhi      NaN     112   26    False

In [28]:
birthyears

alice      1985
yue        1984
ditsuhi    1992
Name: birthyear, dtype: int64

When you add a new colum, it must have the same number of rows. Missing rows are filled with NaN, and extra rows are ignored:

In [29]:
people["pets"] = pd.Series({"bob": 0, "charles": 5, "eugene":1})  # alice is missing, eugene is ignored
people

hobby  weight  age  over 30  pets
alice     Biking      68   33     True   NaN
yue      Dancing      83   34     True   NaN
ditsuhi      NaN     112   26    False   NaN

When adding a new column, it is added at the end (on the right) by default. You can also insert a column anywhere else using the `insert()` method:

In [30]:
people.insert(1, "height", [172, 181, 185])
people

hobby  height  weight  age  over 30  pets
alice     Biking     172      68   33     True   NaN
yue      Dancing     181      83   34     True   NaN
ditsuhi      NaN     185     112   26    False   NaN

## Assigning new columns
You can also create new columns by calling the `assign()` method. Note that this returns a new `DataFrame` object, the original is not modified:

In [31]:
people.assign(
    body_mass_index = people["weight"] / (people["height"] / 100) ** 2,
    has_pets = people["pets"] > 0
)

hobby  height  weight  age  over 30  pets  body_mass_index  \
alice     Biking     172      68   33     True   NaN        22.985398   
yue      Dancing     181      83   34     True   NaN        25.335002   
ditsuhi      NaN     185     112   26    False   NaN        32.724617   

         has_pets  
alice       False  
yue         False  
ditsuhi     False

Note that you cannot access columns created within the same assignment:

In [32]:
try:
    people.assign(
        body_mass_index = people["weight"] / (people["height"] / 100) ** 2,
        overweight = people["body_mass_index"] > 25
    )
except KeyError as e:
    print("Key error:", e)

Key error: 'body_mass_index'


The solution is to split this assignment in two consecutive assignments:

In [33]:
d6 = people.assign(body_mass_index = people["weight"] / (people["height"] / 100) ** 2)
d6.assign(overweight = d6["body_mass_index"] > 25)

hobby  height  weight  age  over 30  pets  body_mass_index  \
alice     Biking     172      68   33     True   NaN        22.985398   
yue      Dancing     181      83   34     True   NaN        25.335002   
ditsuhi      NaN     185     112   26    False   NaN        32.724617   

         overweight  
alice         False  
yue            True  
ditsuhi        True

Having to create a temporary variable `d6` is not very convenient. You may want to just chain the assigment calls, but it does not work because the `people` object is not actually modified by the first assignment:

In [34]:
try:
    (people
         .assign(body_mass_index = people["weight"] / (people["height"] / 100) ** 2)
         .assign(overweight = people["body_mass_index"] > 25)
    )
except KeyError as e:
    print("Key error:", e)

Key error: 'body_mass_index'


You can pass a function to the `assign()` method (typically a `lambda` function), and this function will be called with the `DataFrame` as a parameter:

In [35]:
(people
     .assign(body_mass_index = lambda df: df["weight"] / (df["height"] / 100) ** 2)
     .assign(overweight = lambda df: df["body_mass_index"] > 25)
)

hobby  height  weight  age  over 30  pets  body_mass_index  \
alice     Biking     172      68   33     True   NaN        22.985398   
yue      Dancing     181      83   34     True   NaN        25.335002   
ditsuhi      NaN     185     112   26    False   NaN        32.724617   

         overweight  
alice         False  
yue            True  
ditsuhi        True

Problem solved!

## Evaluating an expression
A great feature supported by pandas is expression evaluation. This relies on the `numexpr` library which must be installed.

In [36]:
people.eval("weight / (height/100) ** 2 > 25")

alice      False
yue         True
ditsuhi     True
dtype: bool

Assignment expressions are also supported. Let's set `inplace=True` to directly modify the `DataFrame` rather than getting a modified copy:

In [37]:
people.eval("body_mass_index = weight / (height/100) ** 2", inplace=True)
people

hobby  height  weight  age  over 30  pets  body_mass_index
alice     Biking     172      68   33     True   NaN        22.985398
yue      Dancing     181      83   34     True   NaN        25.335002
ditsuhi      NaN     185     112   26    False   NaN        32.724617

You can use a local or global variable in an expression by prefixing it with `'@'`:

In [38]:
overweight_threshold = 30
people.eval("overweight = body_mass_index > @overweight_threshold", inplace=True)
people

hobby  height  weight  age  over 30  pets  body_mass_index  \
alice     Biking     172      68   33     True   NaN        22.985398   
yue      Dancing     181      83   34     True   NaN        25.335002   
ditsuhi      NaN     185     112   26    False   NaN        32.724617   

         overweight  
alice         False  
yue           False  
ditsuhi        True

## Querying a `DataFrame`
The `query()` method lets you filter a `DataFrame` based on a query expression:

In [39]:
people.query("age > 30 and pets == 0")

Empty DataFrame
Columns: [hobby, height, weight, age, over 30, pets, body_mass_index, overweight]
Index: []

## Sorting a `DataFrame`
You can sort a `DataFrame` by calling its `sort_index` method. By default it sorts the rows by their index label, in ascending order, but let's reverse the order:

In [40]:
people.sort_index(ascending=False)

hobby  height  weight  age  over 30  pets  body_mass_index  \
yue      Dancing     181      83   34     True   NaN        25.335002   
ditsuhi      NaN     185     112   26    False   NaN        32.724617   
alice     Biking     172      68   33     True   NaN        22.985398   

         overweight  
yue           False  
ditsuhi        True  
alice         False

Note that `sort_index` returned a sorted *copy* of the `DataFrame`. To modify `people` directly, we can set the `inplace` argument to `True`. Also, we can sort the columns instead of the rows by setting `axis=1`:

In [41]:
people.sort_index(axis=1, inplace=True)
people

age  body_mass_index  height    hobby  over 30  overweight  pets  \
alice     33        22.985398     172   Biking     True       False   NaN   
yue       34        25.335002     181  Dancing     True       False   NaN   
ditsuhi   26        32.724617     185      NaN    False        True   NaN   

         weight  
alice        68  
yue          83  
ditsuhi     112

To sort the `DataFrame` by the values instead of the labels, we can use `sort_values` and specify the column to sort by:

In [42]:
people.sort_values(by="age", inplace=True)
people

age  body_mass_index  height    hobby  over 30  overweight  pets  \
ditsuhi   26        32.724617     185      NaN    False        True   NaN   
alice     33        22.985398     172   Biking     True       False   NaN   
yue       34        25.335002     181  Dancing     True       False   NaN   

         weight  
ditsuhi     112  
alice        68  
yue          83

## Operations on `DataFrame`s
Although `DataFrame`s do not try to mimick NumPy arrays, there are a few similarities. Let's create a `DataFrame` to demonstrate this:

In [43]:
grades_array = np.array([[8,8,9],[10,9,9],[4, 8, 2], [9, 10, 10]])
grades = pd.DataFrame(grades_array, columns=["sep", "oct", "nov"], index=["alice","bob","charles","darwin"])
grades

sep  oct  nov
alice      8    8    9
bob       10    9    9
charles    4    8    2
darwin     9   10   10

You can apply NumPy mathematical functions on a `DataFrame`: the function is applied to all values:

In [44]:
np.sqrt(grades)

sep       oct       nov
alice    2.828427  2.828427  3.000000
bob      3.162278  3.000000  3.000000
charles  2.000000  2.828427  1.414214
darwin   3.000000  3.162278  3.162278

Similarly, adding a single value to a `DataFrame` will add that value to all elements in the `DataFrame`. This is called *broadcasting*:

In [45]:
grades + 1

sep  oct  nov
alice      9    9   10
bob       11   10   10
charles    5    9    3
darwin    10   11   11

Of course, the same is true for all other binary operations, including arithmetic (`*`,`/`,`**`...) and conditional (`>`, `==`...) operations:

In [46]:
grades >= 5

sep   oct    nov
alice     True  True   True
bob       True  True   True
charles  False  True  False
darwin    True  True   True

Aggregation operations, such as computing the `max`, the `sum` or the `mean` of a `DataFrame`, apply to each column, and you get back a `Series` object:

In [47]:
grades.mean()

sep    7.75
oct    8.75
nov    7.50
dtype: float64

The `all` method is also an aggregation operation: it checks whether all values are `True` or not. Let's see during which months all students got a grade greater than `5`:

In [48]:
(grades > 5).all()

sep    False
oct     True
nov    False
dtype: bool

Most of these functions take an optional `axis` parameter which lets you specify along which axis of the `DataFrame` you want the operation executed. The default is `axis=0`, meaning that the operation is executed vertically (on each column). You can set `axis=1` to execute the operation horizontally (on each row). For example, let's find out which students had all grades greater than `5`:

In [49]:
(grades > 5).all(axis = 1)

alice       True
bob         True
charles    False
darwin      True
dtype: bool

The `any` method returns `True` if any value is `True`. Let's see who got at least one grade `10`:

In [50]:
(grades == 10).any(axis = 1)

alice      False
bob         True
charles    False
darwin      True
dtype: bool

If you add a `Series` object to a `DataFrame` (or execute any other binary operation), pandas attempts to broadcast the operation to all *rows* in the `DataFrame`. This only works if the `Series` has the same size as the `DataFrame`s rows. For example, let's subtract the `mean` of the `DataFrame` (a `Series` object) from the `DataFrame`:

In [51]:
grades - grades.mean()  # equivalent to: grades - [7.75, 8.75, 7.50]

sep   oct  nov
alice    0.25 -0.75  1.5
bob      2.25  0.25  1.5
charles -3.75 -0.75 -5.5
darwin   1.25  1.25  2.5

We subtracted `7.75` from all September grades, `8.75` from October grades and `7.50` from November grades. It is equivalent to subtracting this `DataFrame`:

In [52]:
pd.DataFrame([[7.75, 8.75, 7.50]]*4, index=grades.index, columns=grades.columns)

sep   oct  nov
alice    7.75  8.75  7.5
bob      7.75  8.75  7.5
charles  7.75  8.75  7.5
darwin   7.75  8.75  7.5

If you want to subtract the global mean from every grade, here is one way to do it:

In [53]:
grades - grades.values.mean() # subtracts the global mean (8.00) from all grades

sep  oct  nov
alice    0.0  0.0  1.0
bob      2.0  1.0  1.0
charles -4.0  0.0 -6.0
darwin   1.0  2.0  2.0

## Automatic alignment
Similar to `Series`, when operating on multiple `DataFrame`s, pandas automatically aligns them by row index label, but also by column names. Let's create a `DataFrame` with bonus points for each person from October to December:

In [54]:
bonus_array = np.array([[0,np.nan,2],[np.nan,1,0],[0, 1, 0], [3, 3, 0]])
bonus_points = pd.DataFrame(bonus_array, columns=["oct", "nov", "dec"], index=["bob","colin", "darwin", "charles"])
bonus_points

oct  nov  dec
bob      0.0  NaN  2.0
colin    NaN  1.0  0.0
darwin   0.0  1.0  0.0
charles  3.0  3.0  0.0

In [55]:
grades + bonus_points

dec   nov   oct  sep
alice    NaN   NaN   NaN  NaN
bob      NaN   NaN   9.0  NaN
charles  NaN   5.0  11.0  NaN
colin    NaN   NaN   NaN  NaN
darwin   NaN  11.0  10.0  NaN

Looks like the addition worked in some cases but way too many elements are now empty. That's because when aligning the `DataFrame`s, some columns and rows were only present on one side, and thus they were considered missing on the other side (`NaN`). Then adding `NaN` to a number results in `NaN`, hence the result.

## Handling missing data
Dealing with missing data is a frequent task when working with real life data. Pandas offers a few tools to handle missing data.
 
Let's try to fix the problem above. For example, we can decide that missing data should result in a zero, instead of `NaN`. We can replace all `NaN` values by a any value using the `fillna()` method:

In [56]:
(grades + bonus_points).fillna(0)

dec   nov   oct  sep
alice    0.0   0.0   0.0  0.0
bob      0.0   0.0   9.0  0.0
charles  0.0   5.0  11.0  0.0
colin    0.0   0.0   0.0  0.0
darwin   0.0  11.0  10.0  0.0

It's a bit unfair that we're setting grades to zero in September, though. Perhaps we should decide that missing grades are missing grades, but missing bonus points should be replaced by zeros:

In [57]:
fixed_bonus_points = bonus_points.fillna(0)
fixed_bonus_points.insert(0, "sep", 0)
fixed_bonus_points.loc["alice"] = 0
grades + fixed_bonus_points

dec   nov   oct   sep
alice    NaN   9.0   8.0   8.0
bob      NaN   9.0   9.0  10.0
charles  NaN   5.0  11.0   4.0
colin    NaN   NaN   NaN   NaN
darwin   NaN  11.0  10.0   9.0

That's much better: although we made up some data, we have not been too unfair.

Another way to handle missing data is to interpolate. Let's look at the `bonus_points` `DataFrame` again:

In [58]:
bonus_points

oct  nov  dec
bob      0.0  NaN  2.0
colin    NaN  1.0  0.0
darwin   0.0  1.0  0.0
charles  3.0  3.0  0.0

Now let's call the `interpolate` method. By default, it interpolates vertically (`axis=0`), so let's tell it to interpolate horizontally (`axis=1`).

In [59]:
bonus_points.interpolate(axis=1)

oct  nov  dec
bob      0.0  1.0  2.0
colin    NaN  1.0  0.0
darwin   0.0  1.0  0.0
charles  3.0  3.0  0.0

Bob had 0 bonus points in October, and 2 in December. When we interpolate for November, we get the mean: 1 bonus point. Colin had 1 bonus point in November, but we do not know how many bonus points he had in September, so we cannot interpolate, this is why there is still a missing value in October after interpolation. To fix this, we can set the September bonus points to 0 before interpolation.

In [60]:
better_bonus_points = bonus_points.copy()
better_bonus_points.insert(0, "sep", 0)
better_bonus_points.loc["alice"] = 0
better_bonus_points = better_bonus_points.interpolate(axis=1)
better_bonus_points

sep  oct  nov  dec
bob      0.0  0.0  1.0  2.0
colin    0.0  0.5  1.0  0.0
darwin   0.0  0.0  1.0  0.0
charles  0.0  3.0  3.0  0.0
alice    0.0  0.0  0.0  0.0

Great, now we have reasonable bonus points everywhere. Let's find out the final grades:

In [61]:
grades + better_bonus_points

dec   nov   oct   sep
alice    NaN   9.0   8.0   8.0
bob      NaN  10.0   9.0  10.0
charles  NaN   5.0  11.0   4.0
colin    NaN   NaN   NaN   NaN
darwin   NaN  11.0  10.0   9.0

It is slightly annoying that the September column ends up on the right. This is because the `DataFrame`s we are adding do not have the exact same columns (the `grades` `DataFrame` is missing the `"dec"` column), so to make things predictable, pandas orders the final columns alphabetically. To fix this, we can simply add the missing column before adding:

In [62]:
grades["dec"] = np.nan
final_grades = grades + better_bonus_points
final_grades

sep   oct   nov  dec
alice     8.0   8.0   9.0  NaN
bob      10.0   9.0  10.0  NaN
charles   4.0  11.0   5.0  NaN
colin     NaN   NaN   NaN  NaN
darwin    9.0  10.0  11.0  NaN

There's not much we can do about December and Colin: it's bad enough that we are making up bonus points, but we can't reasonably make up grades (well I guess some teachers probably do). So let's call the `dropna()` method to get rid of rows that are full of `NaN`s:

In [63]:
final_grades_clean = final_grades.dropna(how="all")
final_grades_clean

sep   oct   nov  dec
alice     8.0   8.0   9.0  NaN
bob      10.0   9.0  10.0  NaN
charles   4.0  11.0   5.0  NaN
darwin    9.0  10.0  11.0  NaN

Now let's remove columns that are full of `NaN`s by setting the `axis` argument to `1`:

In [64]:
final_grades_clean = final_grades_clean.dropna(axis=1, how="all")
final_grades_clean

sep   oct   nov
alice     8.0   8.0   9.0
bob      10.0   9.0  10.0
charles   4.0  11.0   5.0
darwin    9.0  10.0  11.0

## Aggregating with `groupby`
Similar to the SQL language, pandas allows grouping your data into groups to run calculations over each group.

First, let's add some extra data about each person so we can group them, and let's go back to the `final_grades` `DataFrame` so we can see how `NaN` values are handled:

In [65]:
final_grades["hobby"] = ["Biking", "Dancing", np.nan, "Dancing", "Biking"]
final_grades

sep   oct   nov  dec    hobby
alice     8.0   8.0   9.0  NaN   Biking
bob      10.0   9.0  10.0  NaN  Dancing
charles   4.0  11.0   5.0  NaN      NaN
colin     NaN   NaN   NaN  NaN  Dancing
darwin    9.0  10.0  11.0  NaN   Biking

Now let's group data in this `DataFrame` by hobby:

In [66]:
grouped_grades = final_grades.groupby("hobby")
grouped_grades

We are ready to compute the average grade per hobby:

In [67]:
grouped_grades.mean()

sep  oct   nov  dec
hobby                        
Biking    8.5  9.0  10.0  NaN
Dancing  10.0  9.0  10.0  NaN

That was easy! Note that the `NaN` values have simply been skipped when computing the means.

## Pivot tables
Pandas supports spreadsheet-like [pivot tables](https://en.wikipedia.org/wiki/Pivot_table) that allow quick data summarization. To illustrate this, let's create a simple `DataFrame`:

In [68]:
bonus_points

oct  nov  dec
bob      0.0  NaN  2.0
colin    NaN  1.0  0.0
darwin   0.0  1.0  0.0
charles  3.0  3.0  0.0

In [69]:
more_grades = final_grades_clean.stack().reset_index()
more_grades.columns = ["name", "month", "grade"]
more_grades["bonus"] = [np.nan, np.nan, np.nan, 0, np.nan, 2, 3, 3, 0, 0, 1, 0]
more_grades

name month  grade  bonus
0     alice   sep    8.0    NaN
1     alice   oct    8.0    NaN
2     alice   nov    9.0    NaN
3       bob   sep   10.0    0.0
4       bob   oct    9.0    NaN
5       bob   nov   10.0    2.0
6   charles   sep    4.0    3.0
7   charles   oct   11.0    3.0
8   charles   nov    5.0    0.0
9    darwin   sep    9.0    0.0
10   darwin   oct   10.0    1.0
11   darwin   nov   11.0    0.0

Now we can call the `pd.pivot_table()` function for this `DataFrame`, asking to group by the `name` column. By default, `pivot_table()` computes the mean of each numeric column:

In [70]:
pd.pivot_table(more_grades, index="name")

bonus      grade
name                        
alice         NaN   8.333333
bob      1.000000   9.666667
charles  2.000000   6.666667
darwin   0.333333  10.000000

We can change the aggregation function by setting the `aggfunc` argument, and we can also specify the list of columns whose values will be aggregated:

In [71]:
pd.pivot_table(more_grades, index="name", values=["grade","bonus"], aggfunc=np.max)

bonus  grade
name                 
alice      NaN    9.0
bob        2.0   10.0
charles    3.0   11.0
darwin     1.0   11.0

We can also specify the `columns` to aggregate over horizontally, and request the grand totals for each row and column by setting `margins=True`:

In [72]:
pd.pivot_table(more_grades, index="name", values="grade", columns="month", margins=True)

month      nov   oct    sep        All
name                                  
alice     9.00   8.0   8.00   8.333333
bob      10.00   9.0  10.00   9.666667
charles   5.00  11.0   4.00   6.666667
darwin   11.00  10.0   9.00  10.000000
All       8.75   9.5   7.75   8.666667

Finally, we can specify multiple index or column names, and pandas will create multi-level indices:

In [73]:
pd.pivot_table(more_grades, index=("name", "month"), margins=True)

bonus  grade
name    month              
alice   nov      NaN   9.00
        oct      NaN   8.00
        sep      NaN   8.00
bob     nov    2.000  10.00
        oct      NaN   9.00
        sep    0.000  10.00
charles nov    0.000   5.00
        oct    3.000  11.00
        sep    3.000   4.00
darwin  nov    0.000  11.00
        oct    1.000  10.00
        sep    0.000   9.00
All            1.125   8.75

## Overview functions
When dealing with large `DataFrames`, it is useful to get a quick overview of its content. 

In [74]:
much_data = np.fromfunction(lambda x,y: (x+y*y)%17*11, (10000, 26))
large_df = pd.DataFrame(much_data, columns=list("ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
large_df[large_df % 16 == 0] = np.nan
large_df.insert(3,"some_text", "Blabla")
large_df

A     B     C some_text      D      E      F     G      H      I  \
0      NaN  11.0  44.0    Blabla   99.0    NaN   88.0  22.0  165.0  143.0   
1     11.0  22.0  55.0    Blabla  110.0    NaN   99.0  33.0    NaN  154.0   
2     22.0  33.0  66.0    Blabla  121.0   11.0  110.0  44.0    NaN  165.0   
3     33.0  44.0  77.0    Blabla  132.0   22.0  121.0  55.0   11.0    NaN   
4     44.0  55.0  88.0    Blabla  143.0   33.0  132.0  66.0   22.0    NaN   
...    ...   ...   ...       ...    ...    ...    ...   ...    ...    ...   
9995   NaN   NaN  33.0    Blabla   88.0  165.0   77.0  11.0  154.0  132.0   
9996   NaN  11.0  44.0    Blabla   99.0    NaN   88.0  22.0  165.0  143.0   
9997  11.0  22.0  55.0    Blabla  110.0    NaN   99.0  33.0    NaN  154.0   
9998  22.0  33.0  66.0    Blabla  121.0   11.0  110.0  44.0    NaN  165.0   
9999  33.0  44.0  77.0    Blabla  132.0   22.0  121.0  55.0   11.0    NaN   

      ...     Q     R     S     T      U      V      W     X      Y      Z  
0     ...  11.0   NaN  11.0  44.0   99.0    NaN   88.0  22.0  165.0  143.0  
1     ...  22.0  11.0  22.0  55.0  110.0    NaN   99.0  33.0    NaN  154.0  
2     ...  33.0  22.0  33.0  66.0  121.0   11.0  110.0  44.0    NaN  165.0  
3     ...  44.0  33.0  44.0  77.0  132.0   22.0  121.0  55.0   11.0    NaN  
4     ...  55.0  44.0  55.0  88.0  143.0   33.0  132.0  66.0   22.0    NaN  
...   ...   ...   ...   ...   ...    ...    ...    ...   ...    ...    ...  
9995  ...   NaN   NaN   NaN  33.0   88.0  165.0   77.0  11.0  154.0  132.0  
9996  ...  11.0   NaN  11.0  44.0   99.0    NaN   88.0  22.0  165.0  143.0  
9997  ...  22.0  11.0  22.0  55.0  110.0    NaN   99.0  33.0    NaN  154.0  
9998  ...  33.0  22.0  33.0  66.0  121.0   11.0  110.0  44.0    NaN  165.0  
9999  ...  44.0  33.0  44.0  77.0  132.0   22.0  121.0  55.0   11.0    NaN  

[10000 rows x 27 columns]

The `head()` method returns the top 5 rows:

In [75]:
large_df.head()

A     B     C some_text      D     E      F     G      H      I  ...  \
0   NaN  11.0  44.0    Blabla   99.0   NaN   88.0  22.0  165.0  143.0  ...   
1  11.0  22.0  55.0    Blabla  110.0   NaN   99.0  33.0    NaN  154.0  ...   
2  22.0  33.0  66.0    Blabla  121.0  11.0  110.0  44.0    NaN  165.0  ...   
3  33.0  44.0  77.0    Blabla  132.0  22.0  121.0  55.0   11.0    NaN  ...   
4  44.0  55.0  88.0    Blabla  143.0  33.0  132.0  66.0   22.0    NaN  ...   

      Q     R     S     T      U     V      W     X      Y      Z  
0  11.0   NaN  11.0  44.0   99.0   NaN   88.0  22.0  165.0  143.0  
1  22.0  11.0  22.0  55.0  110.0   NaN   99.0  33.0    NaN  154.0  
2  33.0  22.0  33.0  66.0  121.0  11.0  110.0  44.0    NaN  165.0  
3  44.0  33.0  44.0  77.0  132.0  22.0  121.0  55.0   11.0    NaN  
4  55.0  44.0  55.0  88.0  143.0  33.0  132.0  66.0   22.0    NaN  

[5 rows x 27 columns]

Of course there's also a `tail()` function to view the bottom 5 rows. You can pass the number of rows you want:

In [76]:
large_df.tail(n=2)

A     B     C some_text      D     E      F     G     H      I  ...  \
9998  22.0  33.0  66.0    Blabla  121.0  11.0  110.0  44.0   NaN  165.0  ...   
9999  33.0  44.0  77.0    Blabla  132.0  22.0  121.0  55.0  11.0    NaN  ...   

         Q     R     S     T      U     V      W     X     Y      Z  
9998  33.0  22.0  33.0  66.0  121.0  11.0  110.0  44.0   NaN  165.0  
9999  44.0  33.0  44.0  77.0  132.0  22.0  121.0  55.0  11.0    NaN  

[2 rows x 27 columns]

The `info()` method prints out a summary of each columns contents:

In [77]:
large_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   A          8823 non-null   float64
 1   B          8824 non-null   float64
 2   C          8824 non-null   float64
 3   some_text  10000 non-null  object 
 4   D          8824 non-null   float64
 5   E          8822 non-null   float64
 6   F          8824 non-null   float64
 7   G          8824 non-null   float64
 8   H          8822 non-null   float64
 9   I          8823 non-null   float64
 10  J          8823 non-null   float64
 11  K          8822 non-null   float64
 12  L          8824 non-null   float64
 13  M          8824 non-null   float64
 14  N          8822 non-null   float64
 15  O          8824 non-null   float64
 16  P          8824 non-null   float64
 17  Q          8824 non-null   float64
 18  R          8823 non-null   float64
 19  S          8824 non-null   float64
 20  T      

Finally, the `describe()` method gives a nice overview of the main aggregated values over each column:
* `count`: number of non-null (not NaN) values
* `mean`: mean of non-null values
* `std`: [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) of non-null values
* `min`: minimum of non-null values
* `25%`, `50%`, `75%`: 25th, 50th and 75th [percentile](https://en.wikipedia.org/wiki/Percentile) of non-null values
* `max`: maximum of non-null values

In [78]:
large_df.describe()

A            B            C            D            E  \
count  8823.000000  8824.000000  8824.000000  8824.000000  8822.000000   
mean     87.977559    87.972575    87.987534    88.012466    87.983791   
std      47.535911    47.535523    47.521679    47.521679    47.535001   
min      11.000000    11.000000    11.000000    11.000000    11.000000   
25%      44.000000    44.000000    44.000000    44.000000    44.000000   
50%      88.000000    88.000000    88.000000    88.000000    88.000000   
75%     132.000000   132.000000   132.000000   132.000000   132.000000   
max     165.000000   165.000000   165.000000   165.000000   165.000000   

                 F            G            H            I            J  ...  \
count  8824.000000  8824.000000  8822.000000  8823.000000  8823.000000  ...   
mean     88.007480    87.977561    88.000000    88.022441    88.022441  ...   
std      47.519371    47.529755    47.536879    47.535911    47.535911  ...   
min      11.000000    11.000000    11.000000    11.000000    11.000000  ...   
25%      44.000000    44.000000    44.000000    44.000000    44.000000  ...   
50%      88.000000    88.000000    88.000000    88.000000    88.000000  ...   
75%     132.000000   132.000000   132.000000   132.000000   132.000000  ...   
max     165.000000   165.000000   165.000000   165.000000   165.000000  ...   

                 Q            R            S            T            U  \
count  8824.000000  8823.000000  8824.000000  8824.000000  8824.000000   
mean     87.972575    87.977559    87.972575    87.987534    88.012466   
std      47.535523    47.535911    47.535523    47.521679    47.521679   
min      11.000000    11.000000    11.000000    11.000000    11.000000   
25%      44.000000    44.000000    44.000000    44.000000    44.000000   
50%      88.000000    88.000000    88.000000    88.000000    88.000000   
75%     132.000000   132.000000   132.000000   132.000000   132.000000   
max     165.000000   165.000000   165.000000   165.000000   165.000000   

                 V            W            X            Y            Z  
count  8822.000000  8824.000000  8824.000000  8822.000000  8823.000000  
mean     87.983791    88.007480    87.977561    88.000000    88.022441  
std      47.535001    47.519371    47.529755    47.536879    47.535911  
min      11.000000    11.000000    11.000000    11.000000    11.000000  
25%      44.000000    44.000000    44.000000    44.000000    44.000000  
50%      88.000000    88.000000    88.000000    88.000000    88.000000  
75%     132.000000   132.000000   132.000000   132.000000   132.000000  
max     165.000000   165.000000   165.000000   165.000000   165.000000  

[8 rows x 26 columns]

# Saving & loading
Pandas can save `DataFrame`s to various backends, including file formats such as CSV, Excel, JSON, HTML and HDF5, or to a SQL database. Let's create a `DataFrame` to demonstrate this:

In [79]:
my_df = pd.DataFrame(
    [["Biking", 68.5, 1985, np.nan], ["Dancing", 83.1, 1984, 3]], 
    columns=["hobby","weight","birthyear","children"],
    index=["alice", "yue"]
)
my_df

hobby  weight  birthyear  children
alice   Biking    68.5       1985       NaN
yue    Dancing    83.1       1984       3.0

## Saving
Let's save it to CSV, HTML and JSON:

In [80]:
my_df.to_csv(f"{RESULTS_PATH}/my_df.csv")
my_df.to_html(f"{RESULTS_PATH}/my_df.html")
my_df.to_json(f"{RESULTS_PATH}/my_df.json")

Done! Let's take a peek at what was saved:

In [81]:
for filename in (f"{RESULTS_PATH}/my_df.csv", f"{RESULTS_PATH}/my_df.html", f"{RESULTS_PATH}/my_df.json"):
    print("#", filename)
    with open(filename, "rt") as f:
        print(f.read())
        print()

# ../results/my_df.csv
,hobby,weight,birthyear,children
alice,Biking,68.5,1985,
yue,Dancing,83.1,1984,3.0


# ../results/my_df.html
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>hobby</th>
      <th>weight</th>
      <th>birthyear</th>
      <th>children</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>alice</th>
      <td>Biking</td>
      <td>68.5</td>
      <td>1985</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>yue</th>
      <td>Dancing</td>
      <td>83.1</td>
      <td>1984</td>
      <td>3.0</td>
    </tr>
  </tbody>
</table>

# ../results/my_df.json
{"hobby":{"alice":"Biking","yue":"Dancing"},"weight":{"alice":68.5,"yue":83.1},"birthyear":{"alice":1985,"yue":1984},"children":{"alice":null,"yue":3.0}}



Note that the index is saved as the first column (with no name) in a CSV file, as `<th>` tags in HTML and as keys in JSON.

## Loading
Now let's load our CSV file back into a `DataFrame`:

In [82]:
my_df_loaded = pd.read_csv(f"{RESULTS_PATH}/my_df.csv", index_col=0)
my_df_loaded

hobby  weight  birthyear  children
alice   Biking    68.5       1985       NaN
yue    Dancing    83.1       1984       3.0